eiffel-community/etos-api

- Dockerfile
eiffel-community/etos#36
Upgrade to python 3.9.0
None
Latest python, latest features
None
person who …
> Upgrade etos api to python 3.9.0

- src/etos_api/lib/validator.py
- src/etos_api/webserver.py
- tests/lib/__init__.py
- tests/lib/test_validator.py
- tox.ini
fixes: eiffel-community/etos#29
Make use of pydantic models to do this validation.
Since we are going to move over to FastAPI and pydantic,
this is not a bad move.
Also added tests for this new library
We could opt out of pydantic and use jsonschema instead.
I decided to use pydantic because I see us using FastAPI and pydantic in the future to restructure this API.
Fail faster
This validator must be updated whenever a change in the test definition is made.
of my knowledge, is …
> Add test suite validation

- src/etos_api/__init__.py
- src/etos_api/library/context_logging.py
- src/etos_api/main.py
- src/etos_api/routers/environment_provider/router.py
- src/etos_api/routers/etos/router.py
- src/etos_api/routers/etos/utilities.py
- src/etos_api/routers/selftest/router.py
eiffel-community/etos#70
Add logging support to ETOS API as released in ETOS Library 1.8.0.
Added a new Logger class just for ETOS API as the ETOS API uses asyncio and it does not support the context based threading.local that is used in ETOS Library.
The context based logging could be implemented into the ETOS Library logging module and be used by everyone. However I noted that it would be very difficult and might make the code in the ETOS Library a lot more complex than it needs to be.
If we start using asyncio more in the future, then this approach should be reconsidered.
Better logging from the start of the ETOS chain.
None! …
> Add logging support to ETOS API

- src/etos_api/library/graphql.py
None
Make aiohttp trust environment variables by default.
None that I could think of.
Enables to use of environment variables such as HTTP_PROXY to be utilized when running GraphQL queries.
May be an unwanted behavior for this to be enabled by default.
by me, under the same open source license (unless …
> Make aiohttp use the environment variables by default

- src/etos_api/library/graphql.py
- src/etos_api/library/graphql_queries.py
- src/etos_api/routers/etos/router.py
- src/etos_api/routers/etos/schemas.py
- src/etos_api/routers/etos/utilities.py
fixes: eiffel-community/etos#73
Add the ability to start ETOS using artifact ID instead of PackageURL string for more explicit IUT selection.
Also ran black on all files.
I opted to keep the packageurl imeplementation instead of removing as it would be a huge breaking change.
We can start tests on a more explicit IUT, instead of relying on the package URL being unique.
None that I can think of.
license and I have the right …
> Added ability to provide artifact ID instead of purl.

- src/etos_api/routers/environment_provider/router.py
fixes: eiffel-community/etos#82
Added a verification that a configuration has been applied to the environment provider before continuing on.
This could be added to the environment provider configure endpoint instead and have it be verified every time, however I believe that the reduction of complexity on the environment provider API is better in this case.
The API will verify the configuration before continuing on and, potentially, fail later.
Another request to the environment provider.
(b) The contribution is based upon previous work that, to the …
> Verify environment provider configuration before continuing

- src/etos_api/routers/etos/utilities.py
fixes: eiffel-community/etos#104
Added a "^" to the regex query for artifact identity in order to speed up the query.
This design is pretty simple but it is unclear to the users. It is also quite dangerous that we allow all users to define the regex for searching for an identity and we might want to look into that.
Right now, however, this is a pretty simple and effective fix.
Less strain on the event repository and, hopefully, some faster response time from ETOS API.
Described a bit in "Alternate Designs" but this behavior is unclear to users.
(b) …
> Make regex query more efficient

- cmd/api/main.go
- internal/responses/responses.go
- internal/responses/responses_test.go
- pkg/application/application.go
- pkg/application/application_test.go
- pkg/v1alpha1/v1alpha1.go
- pkg/v1alpha1/v1alpha1_test.go
eiffel-community/etos#116
added the selftest/ping endpoint, some response handling and an application layer.
One design that I chose not to do here is the one where I have an application that starts the webserver, an API for each version and handlers separated in different packages.
In this design I chose to have the application and server separate and loading in routes to the application which is then used in the server. This means that we have a simpler code-base but it is not as flexible.
My hope is that this simplicity is worth it. (Example of the other style: https://github.com/eiffel-community/eiffel-goer)
Implementation of the first required endpoint.
None
(a) The contribution was …
> Add selftest endpoint and an application layer

- internal/config/config.go
- internal/config/config_test.go
- internal/logging/logging_test.go
- internal/server/server_test.go
- pkg/v1alpha1/environmentprovider.go
- pkg/v1alpha1/v1alpha1.go
- pkg/v1alpha1/v1alpha1_test.go
- test/testconfig/testconfig.go
eiffel-community/etos#116
StartAPI will now configure and verify the configuration of environment provider.
None
This is a feature in the old implementation and is, as such, required.
None at all!
permitted to submit under a different license), as …
> Add environment provider configuration to StartETOS endpoint

- src/etos_api/routers/etos/router.py
With the update to Eiffellib there is a lot more output from items running in threads and it spammed the logs a lot.
Probably because the connection is not properly shut down.
The aclosing helper could have been updated to do 'stop' instead. But I don't know what else that would affect.
The connection closes and the logs are cleaner
None
work with …
> Make sure that the ETOS publisher is properly closed

- src/etos_api/library/docker.py
- src/etos_api/library/validator.py
fixes: eiffel-community/etos#156
This change derives from #38 and that commit can be ignored in this PR.
Verify that we can receive a digest via the docker repository APIs.
I wanted to use the docker cli tool to do this but was not able to get it to work without doing `docker pull`, which we definitely don't want to do.
Tests will fail faster when the test runner does not exist leaving the users with less confusion.
HTTP requests are, relatively, costly and something we have to do on every single run of ETOS. We might have to do some caching of the data if this becomes to heavy.
have the right to submit it under the open source …
> Validate test runner

- python/docs/conf.py
- python/requirements.txt
- python/setup.cfg
- python/src/etos_api/__init__.py
- python/src/etos_api/library/docker.py
- python/src/etos_api/library/utilities.py
- python/src/etos_api/library/validator.py
- python/src/etos_api/main.py
- python/src/etos_api/routers/environment_provider/router.py
- python/src/etos_api/routers/etos/router.py
- python/src/etos_api/routers/etos/schemas.py
- python/src/etos_api/routers/etos/utilities.py
- python/src/etos_api/routers/logs/router.py
- python/tests/library/test_validator.py
- python/tests/test_routers.py
- python/tox.ini
eiffel-community/etos#204
Added optional support for open telemetry.
I also ran black -l 100 and I had to change a few things in the start_etos endpoint where it had too many statements (pylint).
Opentelemetry was used because it is the biggest and most popular tracing framework. I also decided to only support OTLP since that's what I'm going to be using, if any other exporters become required they can be added.
This allows us to detect problems with the ETOS API.
I did not concern myself with traces that span multiple microservices. That is a bigger beast to tackle. …
> Enable opentelemetry support in the ETOS API

- Dockerfile
- deploy/etos-sse/Dockerfile
- python/setup.cfg
- [ETOS Docker API build fails with 3.9.0 base image](https://github.com/eiffel-community/etos/issues/207)
- The change changes the base image to the latest 3.9 base, without locking to a specific minor version.
permitted to submit under a …
> Use Python 3.9 base image instead of 3.9.0

- python/src/etos_api/library/providers/register.py
#56 
Fix a problem where the providers could not be loaded for configuration when running tests.
The problem was that the text we write to ETCD could not be parsed to JSON which is what we do when configuring.
None really.. I could not even parse it using `jq` so it is not valid JSON at all.
Nope
by …
> Make sure we dump providers to JSON before writing

- python/requirements.txt
- python/setup.cfg
- python/src/etos_api/library/docker.py
- python/src/etos_api/routers/etos/router.py
This pull request fixes an issue with parsing the authorization header in the `authorize` function. It handles cases where the `www-authenticate` header is malformed and raises a `ValueError` if no realm is found in the header. Additionally, it adds error handling for failed authentication with the container registry in the `digest` function. The pull request also includes changes to the `validate_suite` function to add OpenTelemetry events for better tracing and error reporting.
Fredrik Fristedt <<fredrik.fristedt@axis.com>>
(b) The contribution …
> Fix authorization header parsing

- Dockerfile
- deploy/etos-sse/Dockerfile
- https://github.com/eiffel-community/etos/issues/235
This change migrates etos-api to Python 3.9 image based on Debian Bookworm.
(c) The contribution was provided …
> Use Debian Bookworm base image

- python/requirements.txt
- python/setup.cfg
- https://github.com/eiffel-community/etos/issues/236
This change updates etos_lib to 4.3.1 which will add field opentelemetry_trace_id to all logstash entries from etos-api. 
in the …
> Step up etos_lib to 4.3.1

- python/requirements.txt
- python/setup.cfg
- python/src/etos_api/library/validator.py
Adding retry when validation test runners withing test suite validation. This will increase resilience against random network outages and other intermittent non-permanent network related problems.
I could have added the retries on several places in the code as there are chains of head requests made throughout the validation code. Although since the validation is fairly quick i opted for one retry to rule them all.
The backoff is currently very rudimentary and short lived, we will not "survive" longer outages with the current code.
(b) The …
> Add retry for testrunner validation

- python/src/etos_api/library/validator.py
- python/tests/test_routers.py
eiffel-community/etos#254
We currently pass validation on suite definition that only contain an empty list. This should not pass. This change adds a simple assertion to make sure the suite definition array is not empty incl. a small test to verify this behavior.
by me, under the same open source …
> Add validation for empty suite definition list

- .github/workflows/build-push.yml
- https://github.com/eiffel-community/etos/issues/261
This change adds a Github workflow to publish ETOS IUT Provider images in the same way as it is done for Log Area Provider and SSE. …
> Add Github publishing workflow for etos-iut

- pkg/sse/v1/sse.go
- https://github.com/eiffel-community/etos/issues/282
This change makes minor improvements in the SSE server to prevent memory leaks.
(c) The contribution was provided …
> Improve defer response.Body.Close() in SSE

- python/src/etos_api/library/docker.py
- python/src/etos_api/library/validator.py
- https://github.com/eiffel-community/etos/issues/286
This change increases the number of test runner validation attempts and adds exponential backoff sleep time between retries.
in the …
> More robust testrunner validation retry logic

- deploy/etos-iut/Dockerfile
- deploy/etos-iut/Dockerfile.dev
- deploy/etos-logarea/Dockerfile.dev
- deploy/etos-sse/Dockerfile.dev
- https://github.com/eiffel-community/etos/issues/287
This change migrates all etos-api Dockerfiles to Go 1.22 base image. This is needed because all etos-api services share the same go.mod file.
permitted to submit under a different license), as …
> Go 1.22 for all etos-api services

- python/src/etos_api/library/validator.py
- https://github.com/eiffel-community/etos/issues/286
This change adds a simple in-memory cache for testrunner validation results to decrease the number of requests to Docker registry. …
> Lazy testrunner validation

- python/pyproject.toml
- python/tox.ini
- https://github.com/eiffel-community/etos/issues/208
This change fixes several fields in `pyproject.toml` that were incorrect since the migration from `setup.cfg`.
(c) …
> Fix incorrect fields in pyproject.toml

- python/src/etos_api/library/docker.py
fixes: eiffel-community/etos#286
The token cache returned an invalid token for the container registry and when using that token on the first request we got an incorrect realm in the www-authenticate header.
If that happens we will now invalidate the cache and do a HEAD request without a token to get a proper www-authenticate.
I also added an expiration modifier so that we expire the tokens in the cache before they expire on the container registry side.
Added a few variable verifications and type hinting that my editor complained about.
We thought about removing the cache entirely but we are not sure if there are rate limits on certain container registries or not and decided to just retry the authentication if it fails.
We will, in some cases, do one more request to the container registry …
> Fix the problem where a wrong realm is found in www-authenticate

- cmd/iut/main.go
- internal/database/database.go
- internal/database/etcd/etcd.go
- pkg/iut/v1alpha1/v1alpha1.go
- python/test-requirements.txt
- https://github.com/eiffel-community/etos/issues/283
This change migrates the generic ETOS IUT Provider to the common etcd client of ETOS API.
(c) The contribution was …
> Use the common etcd client in etos-iut

- .github/workflows/build-push.yml
- Makefile
- manifests/base/api/deployment.yaml
- manifests/base/executionspace/deployment.yaml
- manifests/base/iut/deployment.yaml
- manifests/base/logarea/deployment.yaml
- manifests/base/sse/deployment.yaml
- https://github.com/eiffel-community/etos/issues/343
This change migrates ETOS API container images from `nordix.org/eiffel` to `ghcr.io/eiffel-community`.
References to images outside `etos-api` haven't been changed yet.
```
python/src/etos_api/routers/v1alpha/router.py:                    "SUITE_RUNNER_IMAGE", "registry.nordix.org/eiffel/etos-suite-runner:latest"
python/src/etos_api/routers/v1alpha/router.py:                    "LOG_LISTENER_IMAGE", "registry.nordix.org/eiffel/etos-log-listener:latest"
python/src/etos_api/routers/v1alpha/router.py:                    "registry.nordix.org/eiffel/etos-environment-provider:latest",
```
(a) The contribution was created in whole or in part by me …
> Migrate container images to ghcr.io

- .github/workflows/build-push.yml
This change fixes this error in the "Update manifests" step of the Github docker publishing workflow:
```
Run fjogeleit/yaml-update-action@main
Error: failed to create PR: HttpError: Resource not accessible by integration
```
permitted to submit …
> Fix for "failed to create PR" in the Github image publishing workflow

- deploy/etos-executionspace/Dockerfile
- deploy/etos-iut/Dockerfile
- deploy/etos-logarea/Dockerfile
- deploy/etos-sse/Dockerfile
- internal/executionspace/provider/kubernetes.go
- internal/kubernetes/kubernetes.go
- https://github.com/eiffel-community/etos/issues/277
This change updates the Kubernetes provider job search with the new label `etos.eiffel-community.github.io/id`. The old label `id` is still kept for backward compatibility.
permitted to submit …
> Kubernetes provider: include v1alpha+ label when searching for jobs

- .gitignore
- python/pyproject.toml
- python/src/etos_api/__init__.py
Adding logging intrumentation enables correlation with other Open Telemetry signals, inscreasing observability for ETOS API.
(c) The contribution was provided directly to …
> Add Open Telemetry logging signals

- internal/kubernetes/kubernetes.go
- https://github.com/eiffel-community/etos/issues/361
This change fixes the return of an empty list in `getJobsByIdentifier()` when no jobs are found.
(c) The …
> SSE: kubernetes.go: fix return of empty job list in getJobsByIdentifier()

- python/src/etos_api/library/environment.py
- python/src/etos_api/routers/v0/router.py
- https://github.com/eiffel-community/etos/issues/384
This change increases the expiration time for etcd entries in `library/environment.py`. This prevents testrun configurations from being automatically deleted when testrun duration exceeds 3600 seconds.
by me, under the same open source license …
> library/environment.py: increase etcd lease time

- python/pyproject.toml
- python/src/etos_api/__init__.py
Since the logic to figure out in what environment the service is running
is very limited, we remove the logic and let it be handled better
somewhere outside of the service.
in the file; …
> Remove in-service telemetry signals envrionment logic

- .github/workflows/build-push.yml
- .github/workflows/main.yml
- Makefile
- deploy/etos-keys/Dockerfile
- deploy/etos-keys/Dockerfile.dev
- deploy/etos-keys/docker-compose.yml
- manifests/base/ingress.yaml
- manifests/base/keys/deployment.yaml
- manifests/base/keys/kustomization.yaml
- manifests/base/keys/service-account.yaml
- manifests/base/keys/service.yaml
- manifests/base/kustomization.yaml
- pkg/keys/v1alpha/keys.go
Adding the key service deployment files for the ETOS API.
There is sadly not much I can do about the required private and public keys for this service. The public key is needed by other services and the private key is needed for the key service to deploy making it hard to generate.
Might look into generating a key from the etos repository which holds the primary kustomization file.
We will be able to solve the generation when deploying as part of the Cluster resource.
of my …
> Add deployment files for the key service

- python/src/etos_api/routers/v0/router.py
- python/src/etos_api/routers/v1alpha/router.py
fixes: eiffel-community/etos#388
Added a catch for TimeoutError from the GraphQL server and return a retryable error with header telling clients to retry after 30s.
(c) …
> Catch TimeoutError and return GatewayTimeout to client

- deploy/etos-executionspace/Dockerfile
- deploy/etos-iut/Dockerfile
- deploy/etos-keys/Dockerfile
- deploy/etos-logarea/Dockerfile
- deploy/etos-sse/Dockerfile
This change steps up git version to 2.47.3 as the previous 2.47.2 is no longer available.
person who …
> use git version 2.47.3 in Dockerfiles

- Dockerfile
- python/pyproject.toml
This change updates the version of etos_lib to 5.1.3.
person who certified (a), (b) or (c) and I have not …
> use etos_lib 5.1.3

- .github/workflows/main.yml
- Dockerfile
- python/pyproject.toml
- https://github.com/eiffel-community/etos/issues/435
This change migrates ETOS API docker and main github workflow to Python 3.13.
(c) The contribution was provided …
> upgrade to Python 3.13
