eiffel-community/etos-api

requirements.txt
setup.cfg

N/A
Upgrade to a newer version of gevent which works.
None
N/A
None
person who certified (a), (b) or (c) …

Gevent version did not work with greenlet anymore.

---

src/etos_api/lib/validator.py

fixes: eiffel-community/etos#66
The validator assumed it would get a dictionary, this is not the case. …

Fixes a bug with validation

---

Dockerfile

None
We are using an alpha version of gql and we seem to have a problem with installing aiohttp.
This can be noticed during the build and release process of ETOS 1.5.0 …

Backtrack pip version as we wait for gql to create a release

---

requirements.txt
setup.cfg

N/A
Update to the latest version of ETOS Library
None
Latest and greatest
None
person who certified (a), …

Update to 1.25.0 of ETOS Library

---

src/etos_api/main.py

N/A
Make it possible to change root path for ETOS API
None
This will allow ETOS deployments to be hosted on other root paths than "/"
None at all
(c) The contribution was …

Add root path configuration

---

src/etos_api/main.py

Reverts eiffel-community/etos-api#24
Did not work as expected.

Revert "Add root path configuration"

---

src/etos_api/routers/environment_provider/schemas.py
src/etos_api/routers/etos/schemas.py

eiffel-community/etos-environment-provider#64
Allow dataset to be a list as well. This is to enable the feature from ETOS environment provider.
None
Ability to do dataset permutations
None
permitted to submit under a different license), as …

Allow dataset to be a list

---

src/etos_api/routers/environment_provider/schemas.py
src/etos_api/routers/etos/router.py
src/etos_api/routers/etos/schemas.py

N/A
It was hard for the ETOS client to know when the ETOS API returns a validation error.
None
Easier for ETOS client to know when it's a validation error
None
(c) The …

Add more information on validation failure

---

requirements.txt
setup.cfg

N/A
Had to downgrade multidict as newer versions of that library are no longer compatible with our old version of pip. We are using an old version of pip due to us having conflicts with ETOS library.
We need to fix our packages and versions. Too big of a change for me right now as I am only interested in fixing an issue.
Buildable again
I am building on the pile of crap that is our packages in this repository.
license and …

Make sure ETOS API is buildable

---

.gitignore
Dockerfile
requirements.txt
setup.cfg
src/etos_api/main.py
src/etos_api/routers/logs/__init__.py
src/etos_api/routers/logs/router.py

eiffel-community/etos#148
depends-on: #40 
depends-on: eiffel-community/etos-library#21
depends-on: eiffel-community/etos-suite-runner#38
Add a new log proxy to the log listener in ESR.
None that I can think of.
Will allow the client to listen to this endpoint and get real(-ish)-time logs from ETOS.
None that I can think of.
work with modifications, whether …

Add log proxy

---

src/etos_api/routers/logs/router.py

None
Instead of a, faulty, hard-coded namespace get the namespace from kubernetes or environment variable.
None
Works
None
(c) The contribution was provided directly to …

Get namespace from kubernetes or environment variable

---

src/etos_api/routers/logs/router.py

N/A
Added some debugging for the log items that we send back via SSE.
We are seeing some JSONDecodeErrors on the client side and this would help in the debugging while also making sure that the information gets sent via logstash.
None
Helps with debugging.
None that I can think of
by me, under the …

Log the messages that are sent to cli via SSE

---

manifests/base/deployment.yaml
manifests/base/kustomization.yaml
manifests/base/role.yaml
manifests/base/rolebinding.yaml
manifests/base/secret.yaml
manifests/base/service-account.yaml
manifests/base/service.yaml
manifests/base/sse/deployment.yaml
manifests/base/sse/kustomization.yaml
manifests/base/sse/role.yaml
manifests/base/sse/rolebinding.yaml
manifests/base/sse/service-account.yaml
manifests/base/sse/service.yaml

eiffel-community/etos#188
merge after #44 
Add manifest files to API
We could keep all manifest files in the ETOS repository, but I think letting each component decide on its own versions and having the ETOS repository set the release versions is the correct way.
Kustomize is easier to handle and built into kubectl
None really
work with modifications, whether …

Add kustomization manifest files

---

manifests/base/deployment.yaml
manifests/base/sse/deployment.yaml

N/A
Update to new versions for the next release
None
N/A
N/A
person who certified (a), (b) or (c) and I …

Update manifest versions to the next release

---

pkg/sse/v1/sse.go

None
If the pod is started, but has not gotten an IP yet, then the URL becomes an empty string.
person who …

Fix a bug where the URL becomes an empty string

---

.github/workflows/build-push.yml

#48 
Attempt to fix a race condition where each workflow job tried to push to git at the same time
None really
Won't have failing builds
(c) The contribution was provided …

Move manifest update to its own job

---

.github/workflows/build-push.yml

#50 
Make sure we clone the repository before updating manifests
We could just let it fail, but then it would fail.
(c) The contribution was provided directly to me by …

Make sure we clone the repository

---

.github/workflows/build-push.yml

person who certified (a), (b) or (c) and I have not modified
it.
(d) I understand and agree that this …

Fix the workflow

---

manifests/base/deployment.yaml
python/src/etos_api/__init__.py

Fix the path to the ping endpoint
person who certified (a), (b) or (c) and I have not modified
it.
(d) I …

Fix the path on ping

---

.github/workflows/build-push.yml

person who certified (a), (b) or (c) and I have not modified
it.
(d) I understand and agree that this …

Fix workflow

---

deploy/etos-executionspace/Dockerfile
deploy/etos-iut/Dockerfile
deploy/etos-logarea/Dockerfile
deploy/etos-sse/Dockerfile
python/src/etos_api/routers/v0/router.py
python/src/etos_api/routers/v0/schemas.py

eiffel-community/etos#221
Allow the passing of an event to the ETOS API.
Still needs fixes in the ETOS client
(c) The contribution was provided directly to me by some …

Allow for the passing of a causal event

---

python/src/etos_api/routers/v0/router.py

#90 
The links.add method expects either a str or another event, passing a UUID will raise an exception. Fix by casting to str.
(c) The contribution was provided directly …

Convert UUID to str before adding to links

---

python/src/etos_api/routers/v0/router.py

- https://github.com/eiffel-community/etos/issues/277
person who certified (a), (b) or (c) and I have not …

Make abort request compatible with v1alpha+ job labels
